name: Restful Booker API Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Collection
        run: |
          newman run "Restful Booker API Framework Copy.postman_collection.json" \
          -e "QA.postman_environment.json" \
          -d "booking-data.csv" \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
